name: Node.js CI

on:
  push:
    branches: [ "deployment" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: pm2 restart toir427/index.js
      - run: pm2 restart essentialwords/index.js
